const classImg = {
    Berserker: 'ClassIcon-Warrior-Berserker.webp',
    Gunlancer: 'ClassIcon-Warrior-Gunlancer.webp',
    Destroyer: 'ClassIcon-Warrior-Destroyer.webp',
    Paladin: 'ClassIcon-Warrior-Paladin.webp',
    Slayer: 'ClassIcon-Warrior-Slayer.webp',
    Sorceress: 'ClassIcon-Mage-Sorceress.webp',
    Summoner: 'ClassIcon-Mage-Summoner.webp',
    Arcana: 'ClassIcon-Mage-Arcanist.webp',
    Bard: 'ClassIcon-Mage-Bard.webp',
    Wardancer: 'ClassIcon-Martial_Artist-Wardancer.webp',
    Scrapper: 'ClassIcon-Martial_Artist-Scrapper.webp',
    Soulfist: 'ClassIcon-Martial_Artist-Soulfist.webp',
    Glaiver: 'ClassIcon-Martial_Artist-Glaiver.webp',
    Striker: 'ClassIcon-Martial_Artist-Striker.webp',
    Sharpshooter: 'ClassIcon-Gunner-Sharpshooter.webp',
    Artillerist: 'ClassIcon-Gunner-Artillerist.webp',
    Deadeye: 'ClassIcon-Gunner-Deadeye.webp',
    Machinist: '',
    Gunslinger: 'ClassIcon-Gunner-Gunslinger.webp',
    Deathblade: 'ClassIcon-Assassin-Deathblade.webp',
    Shadowhunter:'ClassIcon-Assassin-Shadowhunter.webp',
    Reaper: 'ClassIcon-Assassin-Reaper.webp',
    Souleater: '',
    Artist: 'ClassIcon-Specialist-Artist.webp',
    Aeromancer: 'ClassIcon-Specialist-Aeromancer.webp',
}

module.exports = classImg